apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-cluster
  region: ap-south-1

nodeGroups:
  - name: sample-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
